CREATE TABLE patients (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    full_name VARCHAR(160) NOT NULL,
    email VARCHAR(255) NOT NULL UNIQUE,
    phone_number VARCHAR(40) NOT NULL,
    date_of_birth DATE NOT NULL
);

CREATE TABLE appointments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    patient_id BIGINT NOT NULL,
    patient_name VARCHAR(160) NOT NULL,
    doctor_name VARCHAR(160) NOT NULL,
    starts_at TIMESTAMP NOT NULL,
    reason VARCHAR(500) NOT NULL,
    status VARCHAR(40) NOT NULL,
    CONSTRAINT uq_appointments_doctor_slot UNIQUE (doctor_name, starts_at)
);
